name: peardrop app integration
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  test:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install Flutter
        uses: subosito/flutter-action@v1.3.2
      - name: Install app dependencies
        run: flutter pub get
      - name: PearDrop App Integration Tests
        run: flutter test
        # For future use with CodeCov
        # run: flutter test --coverage
      # - name: Upload coverage to Codecov
      #   uses: codecov/codecov-action@v1
      #   with:
      #     token: ${{ secrets.CODECOV_TOKEN }}
      #     file: coverage/lcov.info
