name: peardrop
description: A cross-platform AirDrop alternative
version: 0.0.1+6
author: anirudhb, GoldinGuy

dependencies:
  flutter:
    sdk: flutter

  # connectivity: ^0.4.8+6

  cupertino_icons: ^0.1.2

  sliding_up_panel: ^1.0.2

  mime_type: ^0.3.2

  permission_handler: ^5.0.1+1

  file_picker: ^1.9.0+1

  wc_flutter_share: ^0.2.2

  device_info: ^0.4.2+4

  package_info: ^0.4.1

  get_ip:
    path: ../packages/get_ip/

  http: ^0.12.1

  libpeardrop:
    path: ../peardrop_dart/

  flutter_staggered_animations: "^0.1.2"

  file_chooser:
    git:
      url: git://github.com/google/flutter-desktop-embedding.git
      path: plugins/file_chooser
      ref: b0794faf2c000576515aee56ca6bb5bee64cece4
  menubar:
    git:
      url: git://github.com/google/flutter-desktop-embedding.git
      path: plugins/menubar
      ref: b0794faf2c000576515aee56ca6bb5bee64cece4
  window_size:
    git:
      url: git://github.com/google/flutter-desktop-embedding.git
      path: plugins/window_size
      ref: b0794faf2c000576515aee56ca6bb5bee64cece4
  # Plugins from flutter/plugins, with local desktop implementations.
  path_provider: ^1.6.5
  path_provider_fde:
    git:
      url: git://github.com/google/flutter-desktop-embedding.git
      path: plugins/flutter_plugins/path_provider_fde
      ref: b0794faf2c000576515aee56ca6bb5bee64cece4
  shared_preferences: ^0.5.6
  url_launcher: ^5.4.0
  url_launcher_fde:
    git:
      url: git://github.com/google/flutter-desktop-embedding.git
      path: plugins/flutter_plugins/url_launcher_fde
      ref: b0794faf2c000576515aee56ca6bb5bee64cece4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: ^0.7.4

flutter_icons:
  image_path: "assets/images/icon2.png"
  android: true
  ios: true

flutter:
  uses-material-design: true

  assets:
    - assets/images/icon.png
    - assets/images/header1.png
    - assets/images/header2.png
    - assets/images/header3.png

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/externals/fonts/Montserrat-Regular.ttf
        - asset: assets/externals/fonts/Montserrat-Bold.ttf
          weight: 700
    - family: Open Sans
      fonts:
        - asset: assets/externals/fonts/OpenSans-Regular.ttf
        - asset: assets/externals/fonts/OpenSans-SemiBold.ttf
          weight: 500
        - asset: assets/externals/fonts/OpenSans-Bold.ttf
          weight: 700
