name: peardrop
description: A cross-platform airdrop alternative
version: 1.0.0+1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2

  sliding_up_panel: ^1.0.2

  file_picker: ^1.9.0+1

  device_info: ^0.4.2+4

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf
        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 700
    - family: Open Sans
      fonts:
        - asset: assets/fonts/OpenSans-Regular.ttf
        - asset: assets/fonts/OpenSans-SemiBold.ttf
          weight: 500
        - asset: assets/fonts/OpenSans-Bold.ttf
          weight: 700

dependency_overrides:
  sliding_up_panel:
    git:
      url: https://github.com/GoldinGuy/sliding_up_panel
      ref: master
