name: Protocol tests

on:
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  rust:
    name: Test Rust and C-API libs
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Install sccache
        env:
          LINK: https://github.com/mozilla/sccache/releases/download
          SCCACHE_VERSION: 0.2.12
        run: |
          curl -L "$LINK/$SCCACHE_VERSION/sccache-$SCCACHE_VERSION-x86_64-unknown-linux-musl.tar.gz" | tar xz
          echo "::add-path::$PWD/sccache-$SCCACHE_VERSION-x86_64-unknown-linux-musl/"
      - name: Start sccache
        run: sccache --start-server
      - name: Build Rust lib
        run: cargo build -v
        working-directory: ./peardrop_protocol
        env:
          RUSTC_WRAPPER: sccache
      - name: Test Rust lib
        run: cargo test -v
        working-directory: ./peardrop_protocol
        env:
          RUSTC_WRAPPER: sccache
      - name: Build C-API tests
        run: |
          mkdir build && cd build
          cmake .. -DCMAKE_BUILD_TYPE=Debug
          make
        working-directory: ./peardrop_capi/test
        env:
          RUSTC_WRAPPER: sccache
      - name: Test C-API
        run: ./peardrop_capi_tests
        working-directory: ./peardrop_capi/test/build
